### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [egorovsa/json-unflat#1]
Hey there!

I belong to an open source security research community, and a member (@sampaguitas) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Sampaguitas** [comment]
Hi Sergey,

I have made a pull request,

and would appreciate if you could have a look at it.

With best regards,

Timothee

**Comment by egorovsa** [comment]
@Sampaguitas  Hello . I've just published the updated version.
Let me know if you still have an issue.

**Comment by Sampaguitas** [comment]
Thanks,

It's not what I've proposed, but the vulnerability has been patched.

With best regards,

Timothee

**Comment by JamieSlome** [comment]
@egorovsa - if possible, would you kindly update the status of the report:

https://huntr.dev/bounties/9076ebc6-20f8-4d04-96d3-5e1e4b0c8150/

This ensures that the researcher gets rewarded for their work!
