### ISSUE TITLE
Problem with unflatting underscore

### ISSUE THREAD

**Issue by MuellerNicolas** [egorovsa/json-unflat#3]
Hello @egorovsa ,

I've upgraded from version `1.0.1` to `2.0.0` and noticed, that the following content is not unflated correctly:

```json
{
   "VIEWS.PRODUCTS": "foo",
   "VIEWS.PRODUCTS_PER_PAGE": "bar"
}
```

Actual output:
```json
{
     "VIEWS":
        "PRODUCTS_PER_PAGE": "bar"
}
```

Expected (same as version `1.0.1)`:
```json
{
     "VIEWS":
        "PRODUCTS": "foo",
        "PRODUCTS_PER_PAGE": "bar"
}
```

I suspect this is because the second entry starts the same and continues with an underscore.
If this is intentionally, then it should be mentioned in the changelog.
Otherwise this is a bug.

Thank you for your support.

**Comment by egorovsa** [comment]
Hi thanks you for the bug report. New version v.2.0.1 is available now!
Let me know if it works as you expect.
